# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc9c448759a53787cb0b86b81e3c7eefa4796167ce57c863f7be9cd8475cfa601920241ef80be8b1e1c241d31397238a3f7c613a7b93950858e75f9a61e73e95

test:
  secret_key_base: a0884bb35e6cbb52ee595cebcf36a89baf39b595dc75f6d7e5974e8b4792e5e01db2165011c9bb5e2888fe37c0837ec82e4f784865e9f42353c3ce68fafbf138

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
